### ISSUE TITLE
Determinism

### ISSUE THREAD

**Issue by flying-sheep** [yixuan/RSpectra#14]
Hi!

RSpectra seems really cool. However, there doesn’t seem to be a way to make it respect `set.seed()` (and therefore deterministic):

1. The [common code to get eigs](https://github.com/yixuan/RSpectra/blob/c63b8b51163d73412d03223352608f065f52623d/src/eigs_sym.cpp#L14) calls `eigs.init()` without initialization vector
2. The [parameterless init method](https://github.com/yixuan/spectra/blob/71ed57ceacb0a655a26c13dcad1243dc550edd52/include/Spectra/SymEigsBase.h#L306-L311) initializes `SimpleRandom` with seed 0

RSpectra should either

1. generate an init vector from R via `runif(n) - .5` and use it in `eigs.init()` or
2. initialize `SimpleRandom` with `sample(.Machine$integer.max, 1L)` or
3. somehow pass the state of the RNG ([`globalenv()$.Random.seed`](https://stat.ethz.ch/R-manual/R-devel/library/base/html/Random.html) exists as int vector if the RNG has been used) to `SimpleRandom`

**Comment by yixuan** [comment]
As you have pointed out, RSpectra uses a **deterministic** initial vector, so it does not use the RNG in R. I may add the support for user-supplied initial vector in a future release.

**Comment by flying-sheep** [comment]
Oh, of course! I was so distracted by the presence of a RNG that I didn’t think about how you used it.

So we have two reasonable choices:

1. make the default vector dependent on R’s seed (which means that determinism after `set.seed(s)` breaks once when that behavior is implemented, and determinism without `set.seed(s)` is removed)
2. leave the default vector as that one deterministic one and only add the ability to specify a custom one.

Option 1 is like everyone does it: nondeterminism by default, determinism after `set.seed()`. Useful to catch artefacts caused by the deterministic vector happening to have some special properties in some use cases

Option 2 is to make things predictable by default.

I’m a fan of option 1. The last thing you want is paper containing wrong finings because your eigenvectors have artifacts in them. I always develop without `set.seed()` and publish my end results with a seed that makes them 100% reproducible.

**Comment by yixuan** [comment]
I may finally choose option 2, since I believe for most users they don't understand or care about the effect of the initial vector. Strictly speaking, the Lanczos method that RSpectra uses is not a randomized algorithm. Virtually the only thing that is random is the initial vector, and it plays a similar role as the initial value in a Newton iteration. As long as it is not too weird, the final result should only have very tiny dependence on it.

If the default one is really bad, the algorithm is very likely to fail somewhere else so users can catch that. Otherwise users may get confused if they are unaware of the Krylov space algorithm.

For advanced users like you, it is trivial to mimic the behaviour of option 1 by passing an `runif(n)` vector to the function. Does it sound good to you? I'll report here after I add the functionality.

**Comment by flying-sheep** [comment]
Sounds good, yes! Thank you.

**Comment by yixuan** [comment]
Added this feature in the new release. You can now use `eigs(..., opts = list(initvec = ...))`.

**Comment by flying-sheep** [comment]
amazing, thank you very much!
